# Generated by Django 4.2 on 2023-04-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Altcoins_totales',
            fields=[
                ('moneda', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('percentage_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage_profit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Altcoins_porcentajes',
                'verbose_name_plural': 'Altcoins_porcentajes',
                'db_table': 'altcoins_porcentajes',
                'ordering': ['percentage_balance'],
            },
        ),
        migrations.CreateModel(
            name='Balances_totales',
            fields=[
                ('moneda', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Balances_porcentajes',
                'verbose_name_plural': 'Balances_porcentajes',
                'db_table': 'balances_porcentajes',
                'ordering': ['percentage'],
            },
        ),
        migrations.CreateModel(
            name='Estrategia_principal_mensual',
            fields=[
                ('moneda', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('porcentaje_tiempo_invertido', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Estrategia_principal_mensual',
                'verbose_name_plural': 'Estrategia_principal_mensual',
                'db_table': 'estrategia_principal_mensual',
                'ordering': ['porcentaje_tiempo_invertido'],
            },
        ),
    ]
