# Generated by Django 4.2 on 2023-04-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Categoria_Usuario',
                'verbose_name_plural': 'Categoria_Usuarios',
                'db_table': 'Categoria_Usuario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username/Mail')),
                ('email', models.EmailField(default=None, max_length=254, unique=True, verbose_name='email')),
                ('nombre', models.CharField(default=None, max_length=200, verbose_name='nombre')),
                ('direccion', models.CharField(blank=True, default=None, max_length=100, verbose_name='direccion')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('permiso_desde_codigo', 'Este es un permiso creado desde código'), ('segundo_permiso_codigo', 'Este es un segundo permiso creado desde código')],
            },
        ),
    ]
